{
  "metadata": {
    "timestamp": "2025-02-23T04:12:36Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2018-1060",
        "description": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service.",
        "metadata": {
          "published_date": "2018-06-18T14:29:00.213",
          "last_modified_date": "2024-11-21T03:59:05.553",
          "confidence_level": "medium",
          "severity": "high"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": true
        },
        "counts": {
          "public_exploit_count": 2
        },
        "epss": {
          "score": 0.005,
          "percentile": 0.76436
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "attack_vector": "NETWORK",
            "base_score": 7.5
          },
          {
            "source": "secalert@redhat.com",
            "type": "Secondary",
            "cvss_version": "3.0",
            "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
            "attack_vector": "NETWORK",
            "base_score": 4.30000019073486
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "attack_vector": "NETWORK",
            "base_score": 5
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue32981",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2018-06-18T05:00:00.000Z"
            },
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue32981",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2018-06-18T05:00:00.000Z"
            }
          ],
          "repositories": []
        }
      }
    }
  ]
}