{
  "metadata": {
    "timestamp": "2025-02-24T08:15:15Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2019-9054",
        "description": "",
        "metadata": {
          "published_date": "",
          "last_modified_date": "",
          "confidence_level": "low",
          "severity": "n/a"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 1
        },
        "epss": {
          "score": 0,
          "percentile": 0
        },
        "metrics": [],
        "timeline": {
          "references": [],
          "repositories": [
            {
              "type": "repository",
              "url": "https://github.com/FedericoTorres233/CVE-2019-9053-Fixed",
              "description": "CVE-2019-9054 exploit added support for python3 + bug fixes",
              "published": "2024-05-17T01:03:40Z",
              "created": "2024-05-17T00:33:54Z",
              "last_modified": "2024-05-18T00:02:48Z",
              "repo_name": "FedericoTorres233/CVE-2019-9053-Fixed",
              "name": "",
              "stars": 0,
              "forks": 0
            }
          ]
        }
      }
    }
  ]
}