{
  "metadata": {
    "timestamp": "2025-02-25T16:13:58Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2019-9740",
        "description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
        "metadata": {
          "published_date": "2019-03-13T03:29:00.193",
          "last_modified_date": "2024-11-21T04:52:12.640",
          "confidence_level": "low",
          "severity": "medium"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 1
        },
        "epss": {
          "score": 0.00374,
          "percentile": 0.72774
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "attack_vector": "NETWORK",
            "base_score": 6.09999990463257
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "attack_vector": "NETWORK",
            "base_score": 4.30000019073486
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue36276",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2019-03-13T05:00:00.000Z"
            }
          ],
          "repositories": []
        }
      }
    }
  ]
}