{
  "metadata": {
    "timestamp": "2025-02-24T08:15:15Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2021-3426",
        "description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
        "metadata": {
          "published_date": "2021-05-20T13:15:07.753",
          "last_modified_date": "2024-11-21T06:21:28.650",
          "confidence_level": "low",
          "severity": "medium"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "none",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 0
        },
        "epss": {
          "score": 0.00061,
          "percentile": 0.28551
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:A/AC:L/Au:S/C:P/I:N/A:N",
            "attack_vector": "ADJACENT_NETWORK",
            "base_score": 2.70000004768372
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "attack_vector": "ADJACENT_NETWORK",
            "base_score": 5.69999980926514
          }
        ],
        "timeline": {
          "references": [],
          "repositories": []
        }
      }
    }
  ]
}