{
  "metadata": {
    "timestamp": "2025-02-27T00:49:42Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2021-3177",
        "description": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.",
        "metadata": {
          "published": "",
          "last_modified": "",
          "confidence_level": "low",
          "severity": "critical",
          "source": "",
          "status": ""
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": true
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "attack_vector": "NETWORK",
            "base_score": 9.80000019073486
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "attack_vector": "NETWORK",
            "base_score": 7.5
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue42938",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2021-01-19T05:00:00.000Z"
            }
          ],
          "repositories": null
        },
        "epss": {
          "score": 0.02506,
          "percentile": 0.90008
        },
        "counts": {
          "public_exploit_count": 1
        }
      }
    }
  ]
}